architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    annotationProcessor 'net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5'

    // Architectury API. This is optional, and you can comment it out if you don't need it.
//    modImplementation "dev.architectury:architectury:${architectury_api_version}"

//!! MOONLIGHT LIB (REQUIRED)  -------------------------------------------------------------------------------------- \\
    String path = System.getenv('REPOS20_1')

    if (enable_moonlight_test.toBoolean()) {
        //- Repository LOCAL
        modImplementation(files(path + "\\Moonlight\\fabric\\build\\libs\\moonlight-${moonlight_testVersion}-fabric.jar"))
    } else {
        //+ MAVEN
        modImplementation("maven.modrinth:moonlight:${moonlight_mavenVersion}-fabric") // v2.16.12
    }
}
